"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from urllib.parse import urlparse

from configurations import Configuration, values
from pythonjsonlogger import json

BASE_DIR = Path(__file__).resolve().parent.parent

LOG_DIR = BASE_DIR / "logs"
os.makedirs(LOG_DIR, exist_ok=True)


# Application definition
class Dev(Configuration):
    @classmethod
    def post_setup(cls):
        for var_name in [
            "DOCKER_HOST",
            "CELERY_BROKER_URL",
            "CORS_ALLOWED_ORIGINS",
            "SERVERS_DATA_PATH",
        ]:
            assert getattr(cls, var_name), f"{var_name} not defined"

    # region Basic Django --------------------------------------------------------------------------------------
    DOTENV = BASE_DIR / ".env"
    SECRET_KEY = str(values.SecretValue())
    DEBUG = True
    ALLOWED_HOSTS = ["*", "localhost", "127.0.0.1"]

    INSTALLED_APPS = [
        "admin_interface",
        "colorfield",
        "daphne",
        "accounts",
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        "channels",
        "games",
        "servers",
        "api",
        "rest_framework",
        "rest_framework_simplejwt",
        "rest_framework_simplejwt.token_blacklist",
        "django_filters",
        "corsheaders",
        "drf_yasg",
        "docker_manager",
        "request_id",
    ]

    MIDDLEWARE = [
        "request_id.middleware.RequestIdMiddleware",
        "django.middleware.security.SecurityMiddleware",
        "config.middleware.AdminIPRestrictionMiddleware",
        "corsheaders.middleware.CorsMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
    ]

    ROOT_URLCONF = "config.urls"

    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": [],
            "APP_DIRS": True,
            "OPTIONS": {
                "context_processors": [
                    "django.template.context_processors.request",
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                ],
            },
        },
    ]

    WSGI_APPLICATION = "config.wsgi.application"
    ASGI_APPLICATION = "config.asgi.application"

    # region Channels --------------------------------------------------------------------------------------
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [("127.0.0.1", 6379)],
            },
        },
    }
    # endregion

    DATABASES = values.DatabaseURLValue(environ_prefix=None)

    AUTH_USER_MODEL = "accounts.User"

    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]

    LANGUAGE_CODE = "fr-fr"
    TIME_ZONE = "Europe/Paris"
    USE_I18N = True
    USE_TZ = True

    STATIC_URL = "static/"
    STATIC_ROOT = BASE_DIR / "static"
    MEDIA_URL = "media/"
    MEDIA_ROOT = BASE_DIR / "media"

    DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

    CACHES = values.CacheURLValue()

    REQUEST_ID_HEADER = None

    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "filters": {
            "request_id": {
                "()": "request_id.logging.RequestIdFilter",
            },
        },
        "formatters": {
            "verbose": {
                "format": "[%(levelname)s] - %(asctime)s - %(request_id)s - %(filename)s:%(lineno)d - %(message)s",
                "datefmt": "%Y-%m-%d %H:%M:%S",
            },
            "json": {
                "()": json.JsonFormatter,
                "format": "%(levelname)s %(asctime)s %(name)s %(request_id)s %(message)s",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "verbose",
                "filters": ["request_id"],
            },
            "django": {
                "class": "logging.FileHandler",
                "filename": LOG_DIR / "raw" / "django.log",
                "filters": ["request_id"],
                "formatter": "verbose",
            },
            "celery_worker": {
                "class": "logging.FileHandler",
                "filename": LOG_DIR / "raw" / "celery_worker.log",
                "filters": ["request_id"],
                "formatter": "verbose",
            },
            "celery_beat": {
                "class": "logging.FileHandler",
                "filename": LOG_DIR / "raw" / "celery_beat.log",
                "filters": ["request_id"],
                "formatter": "verbose",
            },
            "json_django": {
                "class": "logging.FileHandler",
                "filename": LOG_DIR / "json" / "django.log",
                "filters": ["request_id"],
                "formatter": "json",
            },
            "json_celery_worker": {
                "class": "logging.FileHandler",
                "filename": LOG_DIR / "json" / "celery_worker.log",
                "filters": ["request_id"],
                "formatter": "json",
            },
            "json_celery_beat": {
                "class": "logging.FileHandler",
                "filename": LOG_DIR / "json" / "celery_beat.log",
                "filters": ["request_id"],
                "formatter": "json",
            },
        },
        "root": {
            "handlers": ["console", "django", "json_django"],
            "level": "INFO",
        },
        "loggers": {
            "django": {
                "handlers": ["console", "django", "json_django"],
                "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
                "propagate": False,
            },
            "celery_worker": {
                "handlers": ["console", "celery_worker", "json_celery_worker"],
                "level": os.getenv("CELERY_WORKER_LOG_LEVEL", "INFO"),
                "propagate": False,
            },
            "celery_beat": {
                "handlers": ["console", "django", "json_celery_beat"],
                "level": os.getenv("CELERY_LOG_LEVEL", "INFO"),
                "propagate": False,
            },
        },
    }

    # endregion

    # region REST Framework --------------------------------------------------------------------------------------
    REST_FRAMEWORK = {
        "DEFAULT_AUTHENTICATION_CLASSES": [
            "rest_framework_simplejwt.authentication.JWTAuthentication",
            "rest_framework.authentication.SessionAuthentication",
        ],
        "DEFAULT_PERMISSION_CLASSES": [
            "rest_framework.permissions.IsAuthenticated",
        ],
        "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
        "PAGE_SIZE": 20,
        "DEFAULT_FILTER_BACKENDS": [
            "django_filters.rest_framework.DjangoFilterBackend",
            "rest_framework.filters.SearchFilter",
            "rest_framework.filters.OrderingFilter",
        ],
        "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",
        "DEFAULT_THROTTLE_CLASSES": [
            "rest_framework.throttling.AnonRateThrottle",
            "rest_framework.throttling.UserRateThrottle",
        ],
        "DEFAULT_THROTTLE_RATES": {
            "anon": "0/hour",
            "user": "1000/hour",
        },
    }

    # endregion

    # region CORS --------------------------------------------------------------------------------------
    CORS_ALLOWED_ORIGINS = values.ListValue()

    CORS_ALLOW_CREDENTIALS = True
    # endregion

    # region Celery --------------------------------------------------------------------------------------
    CELERY_BROKER_URL = values.Value()
    # endregion

    # region Docker --------------------------------------------------------------------------------------
    DOCKER_HOST = values.Value(environ_prefix=None)
    SERVERS_DATA_PATH = values.PathValue(environ_required=True)
    # endregion

    # region Simple JWT --------------------------------------------------------------------------------------
    SIMPLE_JWT = {
        "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
        "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
        "ROTATE_REFRESH_TOKENS": True,
        "BLACKLIST_AFTER_ROTATION": True,
        "UPDATE_LAST_LOGIN": True,
        "ALGORITHM": "HS256",
        "SIGNING_KEY": SECRET_KEY,
        "VERIFYING_KEY": None,
        "AUDIENCE": None,
        "ISSUER": None,
        "AUTH_HEADER_TYPES": ("Bearer",),
        "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
        "USER_ID_FIELD": "id",
        "USER_ID_CLAIM": "user_id",
        "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
        "TOKEN_TYPE_CLAIM": "token_type",
        "JTI_CLAIM": "jti",
    }
    # endregion

    # region Server --------------------------------------------------------------------------------------
    SERVER_STOP_TIMEOUT = values.IntegerValue(default=25)
    SERVER_RESTART_TIMEOUT = values.IntegerValue(default=25)
    MAX_MEMORY_GLOBAL = values.Value(
        default=None,
        help_text="Mémoire maximale globale (ex: 16g, 32g)",
        environ_prefix=None,
    )
    MAX_CPU_GLOBAL = values.FloatValue(default=None, help_text="CPU maximal global (ex: 8.0)", environ_prefix=None)
    # endregion

    # region swagger --------------------------------------------------------------------------------------
    SWAGGER_USE_COMPAT_RENDERERS = False
    # endregion

    # region Admin IP Restriction --------------------------------------------------------------------------------------
    ADMIN_IP_RESTRICTION_DISABLED_IN_DEBUG = values.BooleanValue(default=True, environ_prefix=None)
    # endregion


class Prod(Dev):
    # region Basic Django --------------------------------------------------------------------------------------
    DOTENV = BASE_DIR / ".env.prod"
    SECRET_KEY = str(values.SecretValue())
    DEBUG = values.BooleanValue(default=False)
    ALLOWED_HOSTS = values.ListValue(environ_required=True)

    SECURE_SSL_REDIRECT = values.BooleanValue(default=True, environ_prefix=None)
    SESSION_COOKIE_SECURE = values.BooleanValue(default=True, environ_prefix=None)
    CSRF_COOKIE_SECURE = values.BooleanValue(default=True, environ_prefix=None)
    CSRF_TRUSTED_ORIGINS = values.ListValue(environ_required=True, environ_prefix=None)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = "Lax"
    SESSION_SAVE_EVERY_REQUEST = True
    SESSION_COOKIE_AGE = 3600

    # endregion

    # region Channels --------------------------------------------------------------------------------------
    CHANNEL_LAYERS_HOSTS_URL = values.Value(environ_required=True)

    @classmethod
    def post_setup(cls):
        super().post_setup()
        assert cls.SECRET_KEY is not None
        assert cls.ALLOWED_HOSTS and "*" not in cls.ALLOWED_HOSTS
        assert cls.CORS_ALLOWED_ORIGINS

        redis_url = cls.CHANNEL_LAYERS_HOSTS_URL
        parsed = urlparse(redis_url)

        password = parsed.password if parsed.password else None
        host = parsed.hostname or "localhost"
        port = parsed.port or 6379

        cls.CHANNEL_LAYERS = {
            "default": {
                "BACKEND": "channels_redis.core.RedisChannelLayer",
                "CONFIG": {
                    "hosts": [(host, port)],
                },
            },
        }
        if password:
            cls.CHANNEL_LAYERS["default"]["CONFIG"]["password"] = password

    # endregion

    # region REST Framework --------------------------------------------------------------------------------------
    REST_FRAMEWORK = {
        "DEFAULT_AUTHENTICATION_CLASSES": [
            "rest_framework_simplejwt.authentication.JWTAuthentication",
            "rest_framework.authentication.SessionAuthentication",
        ],
        "DEFAULT_PERMISSION_CLASSES": [
            "rest_framework.permissions.IsAuthenticated",
        ],
        "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
        "PAGE_SIZE": 20,
        "DEFAULT_FILTER_BACKENDS": [
            "django_filters.rest_framework.DjangoFilterBackend",
            "rest_framework.filters.SearchFilter",
            "rest_framework.filters.OrderingFilter",
        ],
        "DATETIME_FORMAT": "%Y-%m-%d %H:%M:%S",
        "DEFAULT_THROTTLE_CLASSES": [
            "rest_framework.throttling.AnonRateThrottle",
            "rest_framework.throttling.UserRateThrottle",
        ],
        "DEFAULT_THROTTLE_RATES": {
            "anon": "0/hour",
            "user": "600/hour",
        },
    }
    # endregion

    # region CORS --------------------------------------------------------------------------------------
    CORS_ALLOWED_ORIGINS = values.ListValue(environ_required=True)
    CORS_ALLOW_CREDENTIALS = True
    CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
    CORS_ALLOW_HEADERS = [
        "accept",
        "accept-encoding",
        "authorization",
        "content-type",
        "dnt",
        "origin",
        "user-agent",
        "x-csrftoken",
        "x-requested-with",
    ]
    # endregion

    # region Simple JWT --------------------------------------------------------------------------------------
    SIMPLE_JWT = {
        "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
        "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
        "ROTATE_REFRESH_TOKENS": True,
        "BLACKLIST_AFTER_ROTATION": True,
        "UPDATE_LAST_LOGIN": True,
        "ALGORITHM": "HS256",
        "SIGNING_KEY": SECRET_KEY,
        "VERIFYING_KEY": None,
        "AUDIENCE": None,
        "ISSUER": None,
        "AUTH_HEADER_TYPES": ("Bearer",),
        "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
        "USER_ID_FIELD": "id",
        "USER_ID_CLAIM": "user_id",
        "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
        "TOKEN_TYPE_CLAIM": "token_type",
        "JTI_CLAIM": "jti",
    }
    # endregion

    # region Logging --------------------------------------------------------------------------------------
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "filters": {
            "request_id": {
                "()": "request_id.logging.RequestIdFilter",
            },
            "require_debug_false": {
                "()": "django.utils.log.RequireDebugFalse",
            },
        },
        "formatters": {
            "verbose": {
                "format": "[%(levelname)s] - %(asctime)s - %(request_id)s - %(filename)s:%(lineno)d - %(message)s",
                "datefmt": "%Y-%m-%d %H:%M:%S",
            },
            "json": {
                "()": json.JsonFormatter,
                "format": "%(levelname)s %(asctime)s %(name)s %(request_id)s %(message)s",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "verbose",
                "filters": ["request_id"],
            },
            "django": {
                "class": "logging.handlers.RotatingFileHandler",
                "filename": LOG_DIR / "raw" / "django.log",
                "maxBytes": 10 * 1024 * 1024,
                "backupCount": 5,
                "filters": ["request_id"],
                "formatter": "verbose",
            },
            "celery_worker": {
                "class": "logging.handlers.RotatingFileHandler",
                "filename": LOG_DIR / "raw" / "celery_worker.log",
                "maxBytes": 10 * 1024 * 1024,
                "backupCount": 5,
                "filters": ["request_id"],
                "formatter": "verbose",
            },
            "celery_beat": {
                "class": "logging.handlers.RotatingFileHandler",
                "filename": LOG_DIR / "raw" / "celery_beat.log",
                "maxBytes": 10 * 1024 * 1024,
                "backupCount": 5,
                "filters": ["request_id"],
                "formatter": "verbose",
            },
            "mail_admins": {
                "level": "ERROR",
                "class": "django.utils.log.AdminEmailHandler",
                "filters": ["require_debug_false"],
                "formatter": "verbose",
            },
            "json_django": {
                "class": "logging.handlers.RotatingFileHandler",
                "filename": LOG_DIR / "json" / "django.log",
                "maxBytes": 10 * 1024 * 1024,
                "backupCount": 5,
                "filters": ["request_id"],
                "formatter": "json",
            },
            "json_celery_worker": {
                "class": "logging.handlers.RotatingFileHandler",
                "filename": LOG_DIR / "json" / "celery_worker.log",
                "maxBytes": 10 * 1024 * 1024,
                "backupCount": 5,
                "filters": ["request_id"],
                "formatter": "json",
            },
            "json_celery_beat": {
                "class": "logging.handlers.RotatingFileHandler",
                "filename": LOG_DIR / "json" / "celery_beat.log",
                "maxBytes": 10 * 1024 * 1024,
                "backupCount": 5,
                "filters": ["request_id"],
                "formatter": "json",
            },
        },
        "root": {
            "handlers": ["console", "django", "json_django"],
            "level": "INFO",
        },
        "loggers": {
            "django": {
                "handlers": ["console", "django", "json_django"],
                "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
                "propagate": False,
            },
            "django.security": {
                "handlers": ["console", "django", "json_django", "mail_admins"],
                "level": "WARNING",
                "propagate": False,
            },
            "celery_worker": {
                "handlers": ["console", "celery_worker", "json_celery_worker"],
                "level": os.getenv("CELERY_WORKER_LOG_LEVEL", "INFO"),
                "propagate": False,
            },
            "celery_beat": {
                "handlers": ["console", "celery_beat", "json_celery_beat"],
                "level": os.getenv("CELERY_LOG_LEVEL", "INFO"),
                "propagate": False,
            },
        },
    }
    # endregion


class Preview(Prod):
    DOTENV = BASE_DIR / ".env.preview"


class Test(Dev):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "test.sqlite3",
        }
    }

    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }

    SERVERS_DATA_PATH = BASE_DIR / "test_servers_data"

    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
    CELERY_BROKER_URL = "memory://"
    CELERY_RESULT_BACKEND = "cache"
    CELERY_CACHE_BACKEND = "memory"
